/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as MeuSetorRouteImport } from './routes/meu-setor'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as EquipeAgendaRouteImport } from './routes/equipe-agenda'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ChatAgendamentoRouteImport } from './routes/chat-agendamento'
import { Route as CadastroInicialRouteImport } from './routes/cadastro-inicial'
import { Route as AgendamentosRouteImport } from './routes/agendamentos'
import { Route as IndexRouteImport } from './routes/index'

const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuSetorRoute = MeuSetorRouteImport.update({
  id: '/meu-setor',
  path: '/meu-setor',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeAgendaRoute = EquipeAgendaRouteImport.update({
  id: '/equipe-agenda',
  path: '/equipe-agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatAgendamentoRoute = ChatAgendamentoRouteImport.update({
  id: '/chat-agendamento',
  path: '/chat-agendamento',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroInicialRoute = CadastroInicialRouteImport.update({
  id: '/cadastro-inicial',
  path: '/cadastro-inicial',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentosRoute = AgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendamentos': typeof AgendamentosRoute
  '/cadastro-inicial': typeof CadastroInicialRoute
  '/chat-agendamento': typeof ChatAgendamentoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/equipe-agenda': typeof EquipeAgendaRoute
  '/inicio': typeof InicioRoute
  '/meu-setor': typeof MeuSetorRoute
  '/painel': typeof PainelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendamentos': typeof AgendamentosRoute
  '/cadastro-inicial': typeof CadastroInicialRoute
  '/chat-agendamento': typeof ChatAgendamentoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/equipe-agenda': typeof EquipeAgendaRoute
  '/inicio': typeof InicioRoute
  '/meu-setor': typeof MeuSetorRoute
  '/painel': typeof PainelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendamentos': typeof AgendamentosRoute
  '/cadastro-inicial': typeof CadastroInicialRoute
  '/chat-agendamento': typeof ChatAgendamentoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/equipe-agenda': typeof EquipeAgendaRoute
  '/inicio': typeof InicioRoute
  '/meu-setor': typeof MeuSetorRoute
  '/painel': typeof PainelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendamentos'
    | '/cadastro-inicial'
    | '/chat-agendamento'
    | '/configuracoes'
    | '/equipe-agenda'
    | '/inicio'
    | '/meu-setor'
    | '/painel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendamentos'
    | '/cadastro-inicial'
    | '/chat-agendamento'
    | '/configuracoes'
    | '/equipe-agenda'
    | '/inicio'
    | '/meu-setor'
    | '/painel'
  id:
    | '__root__'
    | '/'
    | '/agendamentos'
    | '/cadastro-inicial'
    | '/chat-agendamento'
    | '/configuracoes'
    | '/equipe-agenda'
    | '/inicio'
    | '/meu-setor'
    | '/painel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendamentosRoute: typeof AgendamentosRoute
  CadastroInicialRoute: typeof CadastroInicialRoute
  ChatAgendamentoRoute: typeof ChatAgendamentoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EquipeAgendaRoute: typeof EquipeAgendaRoute
  InicioRoute: typeof InicioRoute
  MeuSetorRoute: typeof MeuSetorRoute
  PainelRoute: typeof PainelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-setor': {
      id: '/meu-setor'
      path: '/meu-setor'
      fullPath: '/meu-setor'
      preLoaderRoute: typeof MeuSetorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe-agenda': {
      id: '/equipe-agenda'
      path: '/equipe-agenda'
      fullPath: '/equipe-agenda'
      preLoaderRoute: typeof EquipeAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-agendamento': {
      id: '/chat-agendamento'
      path: '/chat-agendamento'
      fullPath: '/chat-agendamento'
      preLoaderRoute: typeof ChatAgendamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-inicial': {
      id: '/cadastro-inicial'
      path: '/cadastro-inicial'
      fullPath: '/cadastro-inicial'
      preLoaderRoute: typeof CadastroInicialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamentos': {
      id: '/agendamentos'
      path: '/agendamentos'
      fullPath: '/agendamentos'
      preLoaderRoute: typeof AgendamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendamentosRoute: AgendamentosRoute,
  CadastroInicialRoute: CadastroInicialRoute,
  ChatAgendamentoRoute: ChatAgendamentoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EquipeAgendaRoute: EquipeAgendaRoute,
  InicioRoute: InicioRoute,
  MeuSetorRoute: MeuSetorRoute,
  PainelRoute: PainelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
